/*
 * Copyright (c) 2025 Nordic Semiconductor ASA
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef IRONSIDE_SE_INTERNAL_API_SERIALIZATION_H_
#define IRONSIDE_SE_INTERNAL_API_SERIALIZATION_H_

#include <stdint.h>

/* IronSide Call identifiers. */

#define IRONSIDE_SE_CALL_ID_PSA_V1                     0
#define IRONSIDE_SE_CALL_ID_UPDATE_V1                  1
#define IRONSIDE_SE_CALL_ID_CPUCONF_V1                 2
#define IRONSIDE_SE_CALL_ID_DVFS_REQ_OPPOINT_V1        3
#define IRONSIDE_SE_CALL_ID_TDD_CONFIGURE_V1           4
#define IRONSIDE_SE_CALL_ID_BOOTMODE_V1                5
#define IRONSIDE_SE_CALL_ID_COUNTER_SET_V1             6
#define IRONSIDE_SE_CALL_ID_COUNTER_GET_V1             7
#define IRONSIDE_SE_CALL_ID_COUNTER_LOCK_V1            8
#define IRONSIDE_SE_CALL_ID_SNAPSHOT_CAPTURE_V1        9
#define IRONSIDE_SE_CALL_ID_EVENTS_ENABLE_V1           10
#define IRONSIDE_SE_CALL_ID_EVENTS_DISABLE_V1          11
#define IRONSIDE_SE_CALL_ID_PERIPHCONF_INLINE_READ_V1  12
#define IRONSIDE_SE_CALL_ID_PERIPHCONF_INLINE_WRITE_V1 13
#define IRONSIDE_SE_CALL_ID_PERIPHCONF_BUFFER_READ_V1  14
#define IRONSIDE_SE_CALL_ID_PERIPHCONF_BUFFER_WRITE_V1 15
#define IRONSIDE_SE_CALL_ID_PERIPHCONF_FINISH_INIT_V1  16

/* PSA arguments. */

#define IRONSIDE_SE_PSA_REQ_IDX_HANDLE  0
#define IRONSIDE_SE_PSA_REQ_IDX_IN_VEC  1
#define IRONSIDE_SE_PSA_REQ_IDX_IN_LEN  2
#define IRONSIDE_SE_PSA_REQ_IDX_OUT_VEC 3
#define IRONSIDE_SE_PSA_REQ_IDX_OUT_LEN 4
#define IRONSIDE_SE_PSA_REQ_IDX_TYPE    6

#define IRONSIDE_SE_PSA_NUM_REQ_ARGS (IRONSIDE_SE_PSA_REQ_IDX_TYPE + 1)

#define IRONSIDE_SE_PSA_RSP_IDX_STATUS 5

/* UPDATE arguments. */

#define IRONSIDE_SE_UPDATE_REQ_IDX_UPDATE_PTR (0)
#define IRONSIDE_SE_UPDATE_RSP_IDX_RETCODE    (0)

/* CPUCONF arguments. */

#define IRONSIDE_SE_CPUCONF_REQ_IDX_CPU_PARAMS   0
#define IRONSIDE_SE_CPUCONF_REQ_IDX_VECTOR_TABLE 1
#define IRONSIDE_SE_CPUCONF_REQ_IDX_MSG_0        2
#define IRONSIDE_SE_CPUCONF_REQ_IDX_MSG_1        3
#define IRONSIDE_SE_CPUCONF_REQ_IDX_MSG_2        4
#define IRONSIDE_SE_CPUCONF_REQ_IDX_MSG_3        5

#define IRONSIDE_SE_CPUCONF_REQ_CPU_PARAMS_CPU_OFFSET (0)
#define IRONSIDE_SE_CPUCONF_REQ_CPU_PARAMS_CPU_MASK   (0xF)
#define IRONSIDE_SE_CPUCONF_REQ_CPU_PARAMS_WAIT_BIT   (1 << 4)

#define IRONSIDE_SE_CPUCONF_RSP_IDX_RETCODE (0)

#define IRONSIDE_SE_CPUCONF_NUM_REQ_ARGS (IRONSIDE_SE_CPUCONF_REQ_IDX_MSG_3 + 1)

/* TDD CONFIGURE arguments. */

#define IRONSIDE_SE_TDD_REQ_IDX_CONFIG  (0)
#define IRONSIDE_SE_TDD_RSP_IDX_RETCODE (0)

/* DVFS REQ OPPOINT arguments .*/

#define IRONSIDE_SE_DVFS_REQ_IDX_OPPOINT (0)
#define IRONSIDE_SE_DVFS_RSP_IDX_RETCODE (0)

/* BOOTMODE arguments. */

#define IRONSIDE_SE_BOOTMODE_REQ_MODE_MODE_MASK (0x3)
#define IRONSIDE_SE_BOOTMODE_REQ_MODE_SECONDARY (0x1)

#define IRONSIDE_SE_BOOTMODE_REQ_IDX_MODE  0
#define IRONSIDE_SE_BOOTMODE_REQ_IDX_MSG_0 1
#define IRONSIDE_SE_BOOTMODE_REQ_IDX_MSG_1 2
#define IRONSIDE_SE_BOOTMODE_REQ_IDX_MSG_2 3
#define IRONSIDE_SE_BOOTMODE_REQ_IDX_MSG_3 4

#define IRONSIDE_SE_BOOTMODE_NUM_REQ_ARGS (IRONSIDE_SE_BOOTMODE_REQ_IDX_MSG_3 + 1)

#define IRONSIDE_SE_BOOTMODE_RSP_IDX_RETCODE (0)

/* COUNTER SET arguments. */

#define IRONSIDE_SE_COUNTER_SET_REQ_IDX_COUNTER_ID (0)
#define IRONSIDE_SE_COUNTER_SET_REQ_IDX_VALUE      (1)
#define IRONSIDE_SE_COUNTER_SET_RSP_IDX_RETCODE    (0)

/* COUNTER GET arguments. */

#define IRONSIDE_SE_COUNTER_GET_REQ_IDX_COUNTER_ID (0)
#define IRONSIDE_SE_COUNTER_GET_RSP_IDX_RETCODE    (0)
#define IRONSIDE_SE_COUNTER_GET_RSP_IDX_VALUE      (1)

/* COUNTER LOCK arguments. */

#define IRONSIDE_SE_COUNTER_LOCK_REQ_IDX_COUNTER_ID (0)
#define IRONSIDE_SE_COUNTER_LOCK_RSP_IDX_RETCODE    (0)

/* EVENTS_ENABLE arguments. */

#define IRONSIDE_SE_EVENTS_ENABLE_REQ_IDX_EVENT_MASK_0 (0) /* LSB of mask */
#define IRONSIDE_SE_EVENTS_ENABLE_REQ_IDX_EVENT_MASK_1 (1) /* MSB of mask */
#define IRONSIDE_SE_EVENTS_ENABLE_RSP_IDX_RETCODE      (0)

/* EVENTS_DISABLE arguments. */

#define IRONSIDE_SE_EVENTS_DISABLE_REQ_IDX_EVENT_MASK_0 (0) /* LSB of mask */
#define IRONSIDE_SE_EVENTS_DISABLE_REQ_IDX_EVENT_MASK_1 (1) /* MSB of mask */
#define IRONSIDE_SE_EVENTS_DISABLE_RSP_IDX_RETCODE      (0)

/* SNAPSHOT CAPTURE arguments. */

#define IRONSIDE_SE_SNAPSHOT_CAPTURE_REQ_IDX_MODE    (0)
#define IRONSIDE_SE_SNAPSHOT_CAPTURE_RSP_IDX_RETCODE (0)

/* Common PERIPHCONF API arguments. */

#define IRONSIDE_SE_PERIPHCONF_COMMON_RSP_DETAIL_STATUS_OFFSET (0)
#define IRONSIDE_SE_PERIPHCONF_COMMON_RSP_DETAIL_STATUS_MASK   (0xFFFF)
#define IRONSIDE_SE_PERIPHCONF_COMMON_RSP_DETAIL_INDEX_OFFSET  (16)
#define IRONSIDE_SE_PERIPHCONF_COMMON_RSP_DETAIL_INDEX_MASK    (0xFFFF << 16)

#define IRONSIDE_SE_PERIPHCONF_COMMON_RSP_IDX_DETAIL 0

/* PERIPHCONF INLINE READ arguments */

#define IRONSIDE_SE_PERIPHCONF_INLINE_READ_REQ_IDX_COUNT    0
#define IRONSIDE_SE_PERIPHCONF_INLINE_READ_REQ_IDX_REGPTR_0 1
#define IRONSIDE_SE_PERIPHCONF_INLINE_READ_REQ_IDX_REGPTR_1 2
#define IRONSIDE_SE_PERIPHCONF_INLINE_READ_REQ_IDX_REGPTR_2 3
#define IRONSIDE_SE_PERIPHCONF_INLINE_READ_REQ_IDX_REGPTR_3 4
#define IRONSIDE_SE_PERIPHCONF_INLINE_READ_REQ_IDX_REGPTR_4 5
#define IRONSIDE_SE_PERIPHCONF_INLINE_READ_REQ_IDX_REGPTR_5 6

#define IRONSIDE_SE_PERIPHCONF_INLINE_READ_RSP_IDX_DETAIL                                          \
	IRONSIDE_SE_PERIPHCONF_COMMON_RSP_IDX_DETAIL
#define IRONSIDE_SE_PERIPHCONF_INLINE_READ_RSP_IDX_VALUE_0 1
#define IRONSIDE_SE_PERIPHCONF_INLINE_READ_RSP_IDX_VALUE_1 2
#define IRONSIDE_SE_PERIPHCONF_INLINE_READ_RSP_IDX_VALUE_2 3
#define IRONSIDE_SE_PERIPHCONF_INLINE_READ_RSP_IDX_VALUE_3 4
#define IRONSIDE_SE_PERIPHCONF_INLINE_READ_RSP_IDX_VALUE_4 5
#define IRONSIDE_SE_PERIPHCONF_INLINE_READ_RSP_IDX_VALUE_5 6

#define IRONSIDE_SE_PERIPHCONF_INLINE_READ_RSP_DETAIL_STATUS_OFFSET                                \
	IRONSIDE_SE_PERIPHCONF_COMMON_RSP_DETAIL_STATUS_OFFSET
#define IRONSIDE_SE_PERIPHCONF_INLINE_READ_RSP_DETAIL_STATUS_MASK                                  \
	IRONSIDE_SE_PERIPHCONF_COMMON_RSP_DETAIL_STATUS_MASK
#define IRONSIDE_SE_PERIPHCONF_INLINE_READ_RSP_DETAIL_INDEX_OFFSET                                 \
	IRONSIDE_SE_PERIPHCONF_COMMON_RSP_DETAIL_INDEX_OFFSET
#define IRONSIDE_SE_PERIPHCONF_INLINE_READ_RSP_DETAIL_INDEX_MASK                                   \
	IRONSIDE_SE_PERIPHCONF_COMMON_RSP_DETAIL_INDEX_MASK

/* PERIPHCONF INLINE WRITE arguments */

#define IRONSIDE_SE_PERIPHCONF_INLINE_WRITE_REQ_IDX_COUNT    0
#define IRONSIDE_SE_PERIPHCONF_INLINE_WRITE_REQ_IDX_REGPTR_0 1
#define IRONSIDE_SE_PERIPHCONF_INLINE_WRITE_REQ_IDX_VALUE_0  2
#define IRONSIDE_SE_PERIPHCONF_INLINE_WRITE_REQ_IDX_REGPTR_1 3
#define IRONSIDE_SE_PERIPHCONF_INLINE_WRITE_REQ_IDX_VALUE_1  4
#define IRONSIDE_SE_PERIPHCONF_INLINE_WRITE_REQ_IDX_REGPTR_2 5
#define IRONSIDE_SE_PERIPHCONF_INLINE_WRITE_REQ_IDX_VALUE_2  6

#define IRONSIDE_SE_PERIPHCONF_INLINE_WRITE_RSP_IDX_DETAIL                                         \
	IRONSIDE_SE_PERIPHCONF_COMMON_RSP_IDX_DETAIL

#define IRONSIDE_SE_PERIPHCONF_INLINE_WRITE_RSP_DETAIL_STATUS_OFFSET                               \
	IRONSIDE_SE_PERIPHCONF_COMMON_RSP_DETAIL_STATUS_OFFSET
#define IRONSIDE_SE_PERIPHCONF_INLINE_WRITE_RSP_DETAIL_STATUS_MASK                                 \
	IRONSIDE_SE_PERIPHCONF_COMMON_RSP_DETAIL_STATUS_MASK
#define IRONSIDE_SE_PERIPHCONF_INLINE_WRITE_RSP_DETAIL_INDEX_OFFSET                                \
	IRONSIDE_SE_PERIPHCONF_COMMON_RSP_DETAIL_INDEX_OFFSET
#define IRONSIDE_SE_PERIPHCONF_INLINE_WRITE_RSP_DETAIL_INDEX_MASK                                  \
	IRONSIDE_SE_PERIPHCONF_COMMON_RSP_DETAIL_INDEX_MASK

/* PERIPHCONF BUFFER READ arguments */

#define IRONSIDE_SE_PERIPHCONF_BUFFER_READ_REQ_IDX_ADDRESS 0
#define IRONSIDE_SE_PERIPHCONF_BUFFER_READ_REQ_IDX_COUNT   1

#define IRONSIDE_SE_PERIPHCONF_BUFFER_READ_RSP_IDX_DETAIL                                          \
	IRONSIDE_SE_PERIPHCONF_COMMON_RSP_IDX_DETAIL

#define IRONSIDE_SE_PERIPHCONF_BUFFER_READ_RSP_DETAIL_STATUS_OFFSET                                \
	IRONSIDE_SE_PERIPHCONF_COMMON_RSP_DETAIL_STATUS_OFFSET
#define IRONSIDE_SE_PERIPHCONF_BUFFER_READ_RSP_DETAIL_STATUS_MASK                                  \
	IRONSIDE_SE_PERIPHCONF_COMMON_RSP_DETAIL_STATUS_MASK
#define IRONSIDE_SE_PERIPHCONF_BUFFER_READ_RSP_DETAIL_INDEX_OFFSET                                 \
	IRONSIDE_SE_PERIPHCONF_COMMON_RSP_DETAIL_INDEX_OFFSET
#define IRONSIDE_SE_PERIPHCONF_BUFFER_READ_RSP_DETAIL_INDEX_MASK                                   \
	IRONSIDE_SE_PERIPHCONF_COMMON_RSP_DETAIL_INDEX_MASK

/* PERIPHCONF BUFFER WRITE arguments */

#define IRONSIDE_SE_PERIPHCONF_BUFFER_WRITE_REQ_IDX_ADDRESS 0
#define IRONSIDE_SE_PERIPHCONF_BUFFER_WRITE_REQ_IDX_COUNT   1

#define IRONSIDE_SE_PERIPHCONF_BUFFER_WRITE_RSP_IDX_DETAIL                                         \
	IRONSIDE_SE_PERIPHCONF_COMMON_RSP_IDX_DETAIL

#define IRONSIDE_SE_PERIPHCONF_BUFFER_WRITE_RSP_DETAIL_STATUS_OFFSET                               \
	IRONSIDE_SE_PERIPHCONF_COMMON_RSP_DETAIL_STATUS_OFFSET
#define IRONSIDE_SE_PERIPHCONF_BUFFER_WRITE_RSP_DETAIL_STATUS_MASK                                 \
	IRONSIDE_SE_PERIPHCONF_COMMON_RSP_DETAIL_STATUS_MASK
#define IRONSIDE_SE_PERIPHCONF_BUFFER_WRITE_RSP_DETAIL_INDEX_OFFSET                                \
	IRONSIDE_SE_PERIPHCONF_COMMON_RSP_DETAIL_INDEX_OFFSET
#define IRONSIDE_SE_PERIPHCONF_BUFFER_WRITE_RSP_DETAIL_INDEX_MASK                                  \
	IRONSIDE_SE_PERIPHCONF_COMMON_RSP_DETAIL_INDEX_MASK

/* PERIPHCONF FINISH INIT arguments */
#define IRONSIDE_SE_PERIPHCONF_FINISH_INIT_RSP_IDX_RETCODE (0)

#endif /* IRONSIDE_SE_INTERNAL_API_SERIALIZATION_H_ */
