# This is the Jenkins ci variant of the .github/labler.yaml

"CI-run-zephyr-twister":
  - any:
      - "!.github/**/*"
      - "!doc/**/*"
      - "!CODEOWNERS"
      - "!LICENSE"
      - "!**/*.rst"
      - "!VERSION"
      - "!submanifests/**/*"
      - "!MAINTAINERS.yml"
      - "!version.h.in"
      - "!Jenkinsfile"
      - "!**/*.md"

"CI-iot-zephyr-lwm2m-test":
  - "drivers/console/**/*"
  - "drivers/flash/**/*"
  - "subsys/dfu/boot/**/*"
  - "subsys/net/ip/**/*"
  - "subsys/net/lib/http/**/*"
  - "subsys/net/lib/lwm2m//**/*"
  - "subsys/net/**/*"

"CI-iot-samples-test":
  - "boards/arm/nrf9160dk_nrf9160/**/*"
  - "dts/arm/nordic/nrf9160*"
  - "include/net/**/*"
  - "subsys/net/lib/**/*"

"CI-iot-libraries-test":
  - "boards/arm/nrf9160dk_nrf9160/**/*"
  - "dts/arm/nordic/nrf9160*"
  - "include/net/socket_ncs.h"
  - "subsys/testsuite/ztest/**/*"

"CI-lwm2m-test": null
# Not necessary to run tests on changes to this repo.

"CI-boot-dfu-test":
  - "subsys/mgmt/mcumgr/**/*"
  - "subsys/dfu/**/*"
  - "include/mgmt/mcumgr/**/*"
  - "include/dfu/**/*"
  - "samples/subsys/mgmt/mcumgr/smp_svr/**/*"

"CI-tfm-test":
  - "boards/arm/nrf5340dk_nrf5340/**/*"
  - "boards/arm/nrf9160dk_nrf9160/**/*"
  - "drivers/entropy/*"
  - "dts/arm/nordic/nrf5340*"
  - "dts/arm/nordic/nrf9160*"
  - "modules/trusted-firmware-m/**/*"
  - "samples/tfm_integration/**/*"

"CI-ble-test":
  - any:
      - "drivers/bluetooth/**/*"
  - any:
      - "dts/arm/nordic/nrf5*"
  - any:
      - "subsys/bluetooth/**/*"
      - "!subsys/bluetooth/mesh/**/*"
      - "!subsys/bluetooth/audio/**/*"
  - any:
      - "include/zephyr/bluetooth/**/*"
      - "!include/zephyr/bluetooth/mesh/**/*"
  - "samples/bluetooth/hci_rpc/**/*"

"CI-mesh-test":
  - "subsys/bluetooth/mesh/**/*"
  - "include/zephyr/bluetooth/mesh/**/*"
  - "samples/bluetooth/mesh/**/*"
  - "samples/bluetooth/mesh_demo/**/*"
  - "samples/bluetooth/mesh_provisioner/**/*"
  - "tests/bluetooth/mesh/**/*"
  - "tests/bluetooth/mesh_shell/**/*"

"CI-zigbee-test":
  - "subsys/mgmt/mcumgr/**/*"
  - "subsys/dfu/**/*"
  - "include/mgmt/mcumgr/**/*"
  - "include/dfu/**/*"

"CI-thingy91-test":
  - "boards/arm/nrf9160dk_nrf9160/**/*"
  - "arch/x86/core/**/*"
  - "arch/x86/include/**/*"
  - "drivers/console/**/*"
  - "drivers/ethernet/**/*"
  - "drivers/flash/**/*"
  - "drivers/hwinfo/**/*"
  - "drivers/interrupt_controller/**/*"
  - "drivers/net/**/*"
  - "drivers/serial/**/*"
  - "drivers/timer/**/*"
  - "include/**/*"
  - "kernel/**/*"
  - "lib/libc/common/source/stdlib/**/*"
  - "lib/libc/newlib/**/*"
  - "lib/libc/picolibc/**/*"
  - "lib/os/**/*"
  - "lib/posix/**/*"
  - "misc/**/*"
  - "modules/mbedtls/**/*"
  - "soc/x86/ia32/**/*"
  - "subsys/fs/fcb/**/*"
  - "subsys/logging/**/*"
  - "subsys/net/**/*"
  - "subsys/random/**/*"
  - "subsys/settings/include/**/*"
  - "subsys/settings/src/**/*"
  - "subsys/stats/**/*"
  - "subsys/storage/flash_map/**/*"
  - "subsys/storage/stream/**/*"
  - "subsys/tracing/**/*"

"CI-desktop-test":
  - any:
      - "**/*"
      - "!samples/bluetooth/**/*"
      - "!tests/bluetooth/**/*"

"CI-crypto-test":
  - "boards/arm/nrf52840dk_nrf52840/**/*"
  - "boards/arm/nrf5340dk_nrf5340/**/*"
  - "boards/arm/nrf9160dk_nrf9160/**/*"
  - "drivers/entropy/*"
  - "drivers/serial/**/*"
  - "dts/arm/nordic/nrf52840*"
  - "dts/arm/nordic/nrf5340*"
  - "dts/arm/nordic/nrf9160*"
  - "include/drivers/serial/**/*"
  - "modules/mbedtls/**/*"

"CI-fem-test":
  - any:
      - "**/*"
      - "!samples/bluetooth/**/*"
      - "!tests/bluetooth/**/*"

"CI-rs-test":
  - any:
      - "**/*"
      - "!samples/bluetooth/**/*"
      - "!tests/bluetooth/**/*"

"CI-thread-test":
  - "include/zephyr/net/**/*"
  - "modules/mbedtls/**/*"
  - "modules/openthread/**/*"
  - "samples/net/openthread/**/*"
  - "soc/arm/nordic_nrf/**/*"
  - "subsys/net/**/*"
  - "subsys/settings/**/*"

"CI-nfc-test":
  - any:
      - "**/*"
      - "!samples/bluetooth/**/*"
      - "!tests/bluetooth/**/*"

"CI-matter-test":
  - "include/dfu/**/*"
  - "include/mgmt/mcumgr/**/*"
  - "soc/arm/nordic_nrf/**/*"
  - "subsys/dfu/**/*"
  - "subsys/settings/**/*"
  - "subsys/net/**/*"
  - "subsys/mgmt/mcumgr/**/*"
  - "drivers/net/**/*"
  - "samples/bluetooth/hci_rpc/**/*"
  - any:
      - "subsys/bluetooth/**/*"
      - "!subsys/bluetooth/mesh/**/*"
      - "!subsys/bluetooth/audio/**/*"

"CI-find-my-test":
  - any:
      - "**/*"
      - "!samples/bluetooth/**/*"
      - "!tests/bluetooth/**/*"

"CI-gazell-test":
  - any:
      - "**/*"
      - "!samples/bluetooth/**/*"
      - "!tests/bluetooth/**/*"

"CI-rpc-test":
  - any:
      - "**/*"
      - "!samples/bluetooth/**/*"
      - "!tests/bluetooth/**/*"

"CI-modemshell-test":
  - "include/net/**/*"
  - "include/posix/**/*"
  - "include/shell/**/*"
  - "drivers/net/**/*"
  - "drivers/serial/**/*"
  - "drivers/wifi/**/*"
  - "subsys/shell/**/*"
  - "subsys/net/**/*"
  - "subsys/settings/**/*"

"CI-positioning-test":
  - "include/net/**/*"
  - "include/posix/**/*"
  - "drivers/net/**/*"
  - "drivers/wifi/**/*"
  - "subsys/net/**/*"
  - "subsys/settings/**/*"

"CI-cloud-test":
  - "include/zephyr/dfu/**/*"
  - "include/zephyr/net/**/*"
  - "include/zephyr/posix/**/*"
  - "include/zephyr/settings/**/*"
  - "drivers/led/**/*"
  - "drivers/net/**/*"
  - "drivers/sensor/**/*"
  - "drivers/serial/**/*"
  - "drivers/wifi/**/*"
  - "lib/posix/**/*"
  - "soc/arm/nordic_nrf/**/*"
  - "subsys/dfu/**/*"
  - "subsys/net/**/*"
  - "subsys/settings/**/*"

"CI-wifi":
  - "subsys/net/l2/wifi/**/*"
  - "subsys/net/l2/ethernet/**/*"

"CI-sidewalk-test":
  - "include/dfu/**/*"
  - "include/mgmt/mcumgr/**/*"
  - "soc/arm/nordic_nrf/**/*"
  - "subsys/dfu/**/*"
  - "subsys/settings/**/*"
  - "subsys/mgmt/mcumgr/**/*"
  - "samples/bluetooth/hci_rpc/**/*"
  - any:
      - "subsys/bluetooth/**/*"
      - "!subsys/bluetooth/mesh/**/*"
      - "!subsys/bluetooth/audio/**/*"

"CI-audio-test":
  - "boards/arm/nrf5340_audio_dk_nrf5340/**/*"
  - "drivers/flash/**/*"
  - "drivers/spi/**/*"
  - "drivers/gpio/**/*"
  - "drivers/i2c/**/*"
  - "drivers/watchdog/**/*"
  - "include/dfu/**/*"
  - "include/mgmt/mcumgr/**/*"
  - "samples/bluetooth/hci_rpc/**/*"
  - "soc/arm/nordic_nrf/**/*"
  - "subsys/bluetooth/audio/**/*"
  - "subsys/bluetooth/host/**/*"
  - "subsys/dfu/**/*"
  - "subsys/fs/**/*"
  - "subsys/mgmt/mcumgr/**/*"
  - "subsys/sd/**/*"
  - "subsys/storage/**/*"
  - "subsys/task_wdt/**/*"
  - "subsys/usb/**/*"
  - "subsys/zbus/**/*"

"CI-pmic-samples-test":
  - "samples/shields/npm1300_ek/**/*"
  - "boards/shields/npm1300_ek/**/*"
  - "**/**npm1300**/**"
  - "drivers/regulator/regulator_common.c"
  - "drivers/regulator/regulator_shell.c"
  - "drivers/gpio/gpio_shell.c"
  - "drivers/sensor/sensor_shell.c"

"CI-test-low-level":
  - "dts/**/*"
  - "include/zephyr/**/*"
  - "tests/arch/**/*"
  - "arch/**/*"
  - "tests/kernel/**/*"
  - "kernel/**/*"
  - "tests/drivers/**/*"
  - "drivers/**/*"
  - "samples/subsys/settings/**/*"
  - "subsys/settings/**/*"
  - "samples/subsys/logging/**/*"
  - "subsys/logging/**/*"
  - "samples/sensor/**/*"
  - "samples/hello_world/**/*"
  - "samples/synchronization/**/*"
  - "samples/drivers/watchdog/**/*"
  - "modules/hal_nordic/**/*"
