# This is the Jenkins ci variant of the .github/labler.yaml

"CI-run-zephyr-twister":
  - any:
      - "!.github/**/*"
      - "!doc/**/*"
      - "!CODEOWNERS"
      - "!LICENSE"
      - "!**/*.rst"
      - "!VERSION"
      - "!submanifests/**/*"
      - "!MAINTAINERS.yml"
      - "!version.h.in"
      - "!Jenkinsfile"
      - "!**/*.md"

"CI-iot-zephyr-lwm2m-test":
  - "drivers/console/**/*"
  - "drivers/flash/**/*"
  - "subsys/dfu/boot/**/*"
  - "subsys/net/ip/**/*"
  - "subsys/net/lib/http/**/*"
  - "subsys/net/lib/lwm2m//**/*"
  - "subsys/net/**/*"

"CI-iot-samples-test":
  - "boards/nordic/nrf9160dk/**/*"
  - "dts/arm/nordic/nrf9160*"
  - "include/net/**/*"
  - "subsys/net/lib/**/*"

"CI-iot-libraries-test":
  - "boards/nordic/nrf9160dk/**/*"
  - "dts/arm/nordic/nrf9160*"
  - "include/net/socket_ncs.h"
  - "subsys/testsuite/ztest/**/*"

"CI-lwm2m-test": null
# Not necessary to run tests on changes to this repo.

"CI-boot-test":
  - "boards/nordic/**/*"
  - "subsys/mgmt/mcumgr/**/*"
  - "subsys/dfu/**/*"
  - "include/mgmt/mcumgr/**/*"
  - "include/dfu/**/*"
  - "samples/subsys/mgmt/mcumgr/smp_svr/**/*"
  - "tests/boot/**/*"
  - "tests/subsys/dfu/**/*"
  - "tests/subsys/mgmt/mcumgr/**/*"

"CI-dfu-test":
  - "boards/nordic/**/*"
  - "drivers/bluetooth/**/*"
  - "drivers/console/**/*"
  - "drivers/flash/**/*"
  - "drivers/mbox/**/*"
  - "drivers/serial/**/*"
  - "drivers/spi/**/*"
  - "dts/arm/nordic/nrf54h*"
  - "dts/common/nordic/*"
  - "dts/riscv/nordic/nrf54h*"
  - "include/dfu/**/*"
  - "include/mgmt/mcumgr/**/*"
  - "include/zephyr/**/*"
  - "samples/subsys/mgmt/mcumgr/smp_svr/**/*"
  - "scripts/west_commands/build.py"
  - "scripts/west_commands/flash.py"
  - "scripts/west_commands/runners/core.py"
  - "scripts/west_commands/runners/nrf_common.py"
  - "scripts/west_commands/runners/nrfutil.py"
  - "soc/nordic/nrf54h/**/*"
  - "subsys/bluetooth/**/*"
  - "subsys/dfu/**/*"
  - "subsys/logging/**/*"
  - "subsys/mgmt/mcumgr/**/*"
  - "subsys/tracing/**/*"

"CI-tfm-test":
  - "boards/nordic/nrf5340dk/**/*"
  - "boards/nordic/nrf9160dk/**/*"
  - "drivers/entropy/*"
  - "dts/arm/nordic/nrf5340*"
  - "dts/arm/nordic/nrf9160*"
  - "modules/trusted-firmware-m/**/*"
  - "samples/tfm_integration/**/*"

"CI-ble-test":
  - any:
      - "arch/arm/**/*"
  - any:
      - "drivers/bluetooth/**/*"
  - any:
      - "dts/arm/nordic/nrf5*"
  - any:
      - "subsys/bluetooth/**/*"
      - "!subsys/bluetooth/mesh/**/*"
      - "!subsys/bluetooth/audio/**/*"
  - any:
      - "include/zephyr/bluetooth/**/*"
      - "!include/zephyr/bluetooth/mesh/**/*"
  - any:
      - "boards/nordic/nrf5*"
  - any:
      - "soc/nordic/**/*"
  - any:
      - "subsys/pm/**/*"

"CI-ble-samples-test":
  - any:
      - "drivers/bluetooth/**/*"
  - any:
      - "dts/arm/nordic/nrf5*"
  - any:
      - "subsys/bluetooth/**/*"
      - "!subsys/bluetooth/mesh/**/*"
      - "!subsys/bluetooth/audio/**/*"
  - any:
      - "include/zephyr/bluetooth/**/*"
      - "!include/zephyr/bluetooth/mesh/**/*"
  - "samples/bluetooth/**/*"

"CI-mesh-test":
  - "subsys/bluetooth/mesh/**/*"
  - "include/zephyr/bluetooth/mesh/**/*"
  - "samples/bluetooth/mesh/**/*"
  - "samples/bluetooth/mesh_demo/**/*"
  - "samples/bluetooth/mesh_provisioner/**/*"
  - "tests/bluetooth/mesh/**/*"
  - "tests/bluetooth/mesh_shell/**/*"

"CI-thingy91-test":
  - "boards/nordic/nrf9160dk/**/*"
  - "arch/x86/core/**/*"
  - "arch/x86/include/**/*"
  - "drivers/console/**/*"
  - "drivers/ethernet/**/*"
  - "drivers/flash/**/*"
  - "drivers/hwinfo/**/*"
  - "drivers/interrupt_controller/**/*"
  - "drivers/net/**/*"
  - "drivers/serial/**/*"
  - "drivers/timer/**/*"
  - "include/**/*"
  - "kernel/**/*"
  - "lib/libc/common/source/stdlib/**/*"
  - "lib/libc/newlib/**/*"
  - "lib/libc/picolibc/**/*"
  - "lib/os/**/*"
  - "lib/posix/**/*"
  - "misc/**/*"
  - "modules/mbedtls/**/*"
  - "soc/x86/ia32/**/*"
  - "subsys/fs/fcb/**/*"
  - "subsys/logging/**/*"
  - "subsys/net/**/*"
  - "subsys/random/**/*"
  - "subsys/settings/include/**/*"
  - "subsys/settings/src/**/*"
  - "subsys/stats/**/*"
  - "subsys/storage/flash_map/**/*"
  - "subsys/storage/stream/**/*"
  - "subsys/tracing/**/*"

"CI-desktop-test":
  - "drivers/bluetooth/*"
  - "subsys/bluetooth/*"
  - "include/zephyr/bluetooth/*"

"CI-crypto-test":
  - "boards/nordic/nrf52840dk/**/*"
  - "boards/nordic/nrf5340dk/**/*"
  - "boards/nordic/nrf9160dk/**/*"
  - "drivers/entropy/*"
  - "drivers/serial/**/*"
  - "dts/arm/nordic/nrf52840*"
  - "dts/arm/nordic/nrf5340*"
  - "dts/arm/nordic/nrf9160*"
  - "include/drivers/serial/**/*"
  - "modules/mbedtls/**/*"

"CI-fem-test":
  - "boards/nordic/**/*"
  - "drivers/bluetooth/hci/**/*"
  - "drivers/entropy/**/*"
  - "dts/bindings/**/*"
  - "include/zephyr/net/**/*"
  - "include/zephyr/arch/**/*"
  - "lib/libc/**/*"
  - "lib/open-amp/**/*"
  - "modules/hal_nordic/**/*"
  - "modules/mbedtls/**/*"
  - "modules/openthread/**/*"
  - "modules/trusted-firmware-m/**/*"
  - "samples/net/sockets/echo_*/**/*"
  - "share/**/*"
  - "soc/nordic/**/*"
  - "subsys/net/**/*"
  - "subsys/settings/**/*"
  - "subsys/bluetooth/shell/**/*"
  - "subsys/ipc/**/*"
  - "Kconfig"
  - "CMakeLists.txt"

"CI-rs-test":
  - "boards/nordic/**/*"
  - "drivers/bluetooth/hci/**/*"
  - "drivers/entropy/**/*"
  - "dts/bindings/**/*"
  - "include/zephyr/net/**/*"
  - "include/zephyr/arch/**/*"
  - "lib/libc/**/*"
  - "lib/open-amp/**/*"
  - "modules/hal_nordic/**/*"
  - "modules/mbedtls/**/*"
  - "modules/openthread/**/*"
  - "modules/trusted-firmware-m/**/*"
  - "samples/net/sockets/echo_*/**/*"
  - "share/**/*"
  - "soc/nordic/**/*"
  - "subsys/net/**/*"
  - "subsys/settings/**/*"
  - "subsys/bluetooth/shell/**/*"
  - "subsys/ipc/**/*"
  - "Kconfig"
  - "CMakeLists.txt"

"CI-thread-test":
  - "include/zephyr/net/**/*"
  - "modules/mbedtls/**/*"
  - "modules/openthread/**/*"
  - "samples/net/openthread/**/*"
  - "soc/nordic/**/*"
  - "subsys/net/**/*"
  - "subsys/settings/**/*"

"CI-nfc-test":
  - "drivers/bluetooth/hci/**/*"
  - "drivers/entropy/**/*"
  - "drivers/flash/**/*"
  - "drivers/mbox/**/*"
  - "drivers/spi/**/*"
  - "lib/crc/**/*"
  - "modules/hal_nordic/**/*"
  - "soc/nordic/**/*"
  - "subsys/ipc/ipc_service/**/*"
  - "subsys/fs/**/*"
  - "subsys/mem_mgmt/**/*"
  - "subsys/net/**/*"
  - "subsys/random/**/*"
  - "subsys/settings/**/*"
  - "subsys/shell/**/*"
  - "subsys/storage/**/*"
  - any:
      - "subsys/bluetooth/**/*"
      - "!subsys/bluetooth/mesh/**/*"

"CI-matter-test":
  - "include/dfu/**/*"
  - "include/mgmt/mcumgr/**/*"
  - "soc/nordic/**/*"
  - "subsys/dfu/**/*"
  - "subsys/settings/**/*"
  - "subsys/net/**/*"
  - "subsys/mgmt/mcumgr/**/*"
  - "drivers/net/**/*"
  - "samples/bluetooth/hci_ipc/**/*"
  - any:
      - "subsys/bluetooth/**/*"
      - "!subsys/bluetooth/mesh/**/*"
      - "!subsys/bluetooth/audio/**/*"

"CI-find-my-test":
  - "boards/nordic/nrf52840dk/**/*"
  - "boards/nordic/nrf5340dk/**/*"
  - "boards/nordic/nrf54l15dk/**/*"
  - "drivers/bluetooth/**/*"
  - "drivers/entropy/**/*"
  - "drivers/flash/**/*"
  - "drivers/usb/**/*"
  - "drivers/regulator/**/*"
  - any:
      - "soc/nordic/**/*"
      - "!soc/nordic/nrf51*"
      - "!soc/nordic/nrf54h*"
      - "!soc/nordic/nrf9*"
  - "subsys/dfu/**/*"
  - "subsys/fs/**/*"
  - "subsys/ipc/**/*"
  - "subsys/net/**/*"
  - "subsys/random/**/*"
  - "subsys/settings/**/*"
  - "subsys/storage/**/*"
  - "subsys/tracing/**/*"
  - "subsys/usb/device/**/*"
  - any:
      - "subsys/bluetooth/**/*"
      - "!subsys/bluetooth/mesh/**/*"

"CI-rpc-test":
  - "subsys/ipc/ipc_service/**/*"
  - "subsys/random/**/*"
  - "soc/nordic/nrf53/**/*"

"CI-modemshell-test":
  - "include/net/**/*"
  - "include/posix/**/*"
  - "include/shell/**/*"
  - "drivers/net/**/*"
  - "drivers/serial/**/*"
  - "drivers/wifi/**/*"
  - "subsys/shell/**/*"
  - "subsys/net/**/*"
  - "subsys/settings/**/*"

"CI-positioning-test":
  - "include/net/**/*"
  - "include/posix/**/*"
  - "drivers/net/**/*"
  - "drivers/wifi/**/*"
  - "subsys/net/**/*"
  - "subsys/settings/**/*"

"CI-cloud-test":
  - "include/zephyr/dfu/**/*"
  - "include/zephyr/net/**/*"
  - "include/zephyr/posix/**/*"
  - "include/zephyr/settings/**/*"
  - "drivers/led/**/*"
  - "drivers/net/**/*"
  - "drivers/sensor/**/*"
  - "drivers/serial/**/*"
  - "drivers/wifi/**/*"
  - "lib/posix/**/*"
  - "soc/nordic/nrf9*/*"
  - "subsys/dfu/**/*"
  - "subsys/net/**/*"
  - "subsys/settings/**/*"

"CI-wifi":
  - "subsys/net/l2/wifi/**/*"
  - "subsys/net/l2/ethernet/**/*"

"CI-audio-test":
  - "boards/nordic/nrf5340_audio_dk/**/*"
  - "drivers/flash/**/*"
  - "drivers/spi/**/*"
  - "drivers/gpio/**/*"
  - "drivers/i2c/**/*"
  - "drivers/watchdog/**/*"
  - "include/dfu/**/*"
  - "include/mgmt/mcumgr/**/*"
  - "samples/bluetooth/hci_ipc/**/*"
  - any:
      - "soc/nordic/**/*"
      - "!soc/nordic/nrf51*"
      - "!soc/nordic/nrf52*"
      - "!soc/nordic/nrf54*"
      - "!soc/nordic/nrf9*"
  - "subsys/bluetooth/audio/**/*"
  - "subsys/bluetooth/host/**/*"
  - "subsys/dfu/**/*"
  - "subsys/fs/**/*"
  - "subsys/mgmt/mcumgr/**/*"
  - "subsys/sd/**/*"
  - "subsys/storage/**/*"
  - "subsys/task_wdt/**/*"
  - "subsys/usb/**/*"
  - "subsys/zbus/**/*"

"CI-pmic-samples-test":
  - "samples/shields/npm1300_ek/**/*"
  - "boards/shields/npm1300_ek/**/*"
  - "**/**npm1300**/**"
  - "drivers/regulator/regulator_common.c"
  - "drivers/regulator/regulator_shell.c"
  - "drivers/gpio/gpio_shell.c"
  - "drivers/sensor/sensor_shell.c"

"CI-test-low-level":
  - any:
      - "soc/nordic/**/*"
      - "!soc/nordic/nrf51*"
      - "!soc/nordic/nrf52*"
      - "!soc/nordic/nrf53*"
      - "!soc/nordic/nrf9*"
  - "arch/arm/**/*"
  - "arch/riscv/**/*"
  - "boards/nordic/nrf54*/**/*"
  - "drivers/adc/**/*"
  - "drivers/cache/**/*"
  - "drivers/clock_control/**/*"
  - "drivers/comparator/**/*"
  - "drivers/counter/**/*"
  - "drivers/flash/**/*"
  - "drivers/gpio/**/*"
  - "drivers/hwinfo/**/*"
  - "drivers/i2c/**/*"
  - "drivers/i2s/**/*"
  - "drivers/interrupt_controller/**/*"
  - "drivers/mbox/**/*"
  - "drivers/mspi/**/*"
  - "drivers/pinctrl/**/*"
  - "drivers/power_domain/**/*"
  - "drivers/pwm/**/*"
  - "drivers/retained_mem/**/*"
  - "drivers/rtc/**/*"
  - "drivers/serial/**/*"
  - "drivers/spi/**/*"
  - "drivers/timer/**/*"
  - "drivers/usb/**/*"
  - "drivers/watchdog/**/*"
  - any:
      - "dts/vendor/nordic/**/*"
      - "!dts/vendor/nordic/nrf52*"
      - "!dts/vendor/nordic/nrf53*"
      - "!dts/vendor/nordic/nrf9*"
  - "modules/hal_nordic/**/*"
  - "samples/boards/nordic/**/*"
  - "tests/arch/arm/**/*"
  - "tests/boards/nrf/**/*"
  - "tests/drivers/adc/**/*"
  - "tests/drivers/clock_control/**/*"
  - "tests/drivers/comparator/**/*"
  - "tests/drivers/counter/**/*"
  - "tests/drivers/flash/**/*"
  - "tests/drivers/gpio/**/*"
  - "tests/drivers/hwinfo/**/*"
  - "tests/drivers/i2c/**/*"
  - "tests/drivers/i2s/**/*"
  - "tests/drivers/interrupt_controller/**/*"
  - "tests/drivers/mbox/**/*"
  - "tests/drivers/mspi/**/*"
  - "tests/drivers/pinctrl/**/*"
  - "tests/drivers/pwm/**/*"
  - "tests/drivers/retained_mem/**/*"
  - "tests/drivers/rtc/**/*"
  - "tests/drivers/spi/**/*"
  - "tests/drivers/timer/**/*"
  - "tests/drivers/uart/**/*"
  - "tests/drivers/watchdog/**/*"
  - "tests/kernel/common/**/*"
  - "tests/kernel/context/**/*"
  - "tests/kernel/fatal/**/*"
  - "tests/kernel/fpu_sharing/**/*"
  - "tests/kernel/gen_isr_table/**/*"
  - "tests/kernel/interrupt/**/*"
  - "tests/kernel/sched/preempt/**/*"
