# This is the Jenkins ci variant of the .github/labler.yaml
"CI-iot-zephyr-lwm2m-test":
  - "drivers/console/**/*"
  - "drivers/flash/**/*"
  - "subsys/dfu/boot/**/*"
  - "subsys/net/ip/**/*"
  - "subsys/net/lib/http/**/*"
  - "subsys/net/lib/lwm2m//**/*"
  - "subsys/net/**/*"

"CI-iot-samples-test":
  - "boards/arm/nrf9160dk_nrf9160/**/*"
  - "dts/arm/nordic/nrf9160*"
  - "include/net/**/*"
  - "subsys/net/lib/**/*"

"CI-iot-libraries-test":
  - "boards/arm/nrf9160dk_nrf9160/**/*"
  - "dts/arm/nordic/nrf9160*"
  - "include/net/socket_ncs.h"
  - "subsys/testsuite/ztest/**/*"

"CI-lwm2m-test":
  - "**/*"

"CI-boot-dfu-test":
  - "subsys/mgmt/mcumgr/**/*"
  - "subsys/dfu/**/*"
  - "include/mgmt/mcumgr/**/*"
  - "include/dfu/**/*"
  - "samples/subsys/mgmt/mcumgr/smp_svr/**/*"

"CI-tfm-test":
  - "**/*"

"CI-ble-test":
  - "**/*"

"CI-mesh-test":
  - "subsys/bluetooth/mesh/**/*"
  - "include/bluetooth/mesh/**/*"
  - "samples/bluetooth/mesh/**/*"
  - "samples/bluetooth/mesh_demo/**/*"
  - "samples/bluetooth/mesh_provisioner/**/*"
  - "tests/bluetooth/mesh/**/*"
  - "tests/bluetooth/mesh_shell/**/*"

"CI-zigbee-test":
  - "subsys/mgmt/mcumgr/**/*"
  - "subsys/dfu/**/*"
  - "include/mgmt/mcumgr/**/*"
  - "include/dfu/**/*"

"CI-thingy91-test":
  - "**/*"

"CI-desktop-test":
  - "**/*"

"CI-crypto-test":
  - "**/*"

"CI-rs-test":
  - "**/*"

"CI-homekit-test":
  - "include/dfu/**/*"
  - "include/mgmt/mcumgr/**/*"
  - "soc/arm/nordic_nrf/**/*"
  - "subsys/dfu/**/*"
  - "subsys/settings/**/*"
  - "subsys/net/lib/openthread/**/*"
  - "subsys/mgmt/mcumgr/**/*"
  - "samples/hci_rpmsg/**/*"
  - "samples/subsys/mgmt/mcumgr/smp_svr/**/*"
  - any:
    - "subsys/bluetooth/**/*"
    - "!subsys/bluetooth/mesh/**/*"

"CI-thread-test":
  - "**/*"

"CI-nfc-test":
  - "**/*"

"CI-matter-test":
  - "include/dfu/**/*"
  - "include/mgmt/mcumgr/**/*"
  - "soc/arm/nordic_nrf/**/*"
  - "subsys/dfu/**/*"
  - "subsys/settings/**/*"
  - "subsys/net/**/*"
  - "subsys/mgmt/mcumgr/**/*"
  - "drivers/net/**/*"
  - "samples/hci_rpmsg/**/*"
  - any:
    - "subsys/bluetooth/**/*"
    - "!subsys/bluetooth/mesh/**/*"
    - "!subsys/bluetooth/audio/**/*"

"CI-find-my-test":
  - "**/*"

"CI-gazell-test":
  - "**/*"

"CI-rpc-test":
  - "**/*"

"CI-modemshell-test":
  - "include/net/**/*"
  - "include/posix/**/*"
  - "include/shell/**/*"
  - "drivers/net/**/*"
  - "drivers/serial/**/*"
  - "drivers/wifi/**/*"
  - "subsys/shell/**/*"
  - "subsys/net/**/*"
  - "subsys/settings/**/*"

"CI-positioning-test":
  - "include/net/**/*"
  - "include/posix/**/*"
  - "drivers/net/**/*"
  - "drivers/wifi/**/*"
  - "subsys/net/**/*"
  - "subsys/settings/**/*"

"CI-cloud-test":
  - "include/zephyr/dfu/**/*"
  - "include/zephyr/net/**/*"
  - "include/zephyr/posix/**/*"
  - "include/zephyr/settings/**/*"
  - "drivers/led/**/*"
  - "drivers/net/**/*"
  - "drivers/sensor/**/*"
  - "drivers/serial/**/*"
  - "drivers/wifi/**/*"
  - "lib/posix/**/*"
  - "soc/arm/nordic_nrf/**/*"
  - "subsys/dfu/**/*"
  - "subsys/net/**/*"
  - "subsys/settings/**/*"
