# The west manifest file for upstream Zephyr.
#
# The per-installation west configuration file, .west/config, sets the
# path to the project containing this file in the [manifest] section's
# "path" variable.
#
# You are free to create your own manifest files and put them in any
# repository you want, to create your own custom Zephyr installations.
# For example, you could create a manifest file in your own out of
# tree application directory, which would pull this zephyr repository
# in as an ordinary project.
#
# You can pass your manifest repositories to west init when creating a
# new Zephyr installation. See the west documentation for more
# information.

manifest:
  defaults:
    remote: upstream

  remotes:
    - name: upstream
      url-base: https://github.com/zephyrproject-rtos
    - name: trustedfirmware
      url-base: https://git.trustedfirmware.org
    - name: trustedfirmware-nordic
      url-base: https://github.com/NordicPlayground
    - name: ARM-software
      url-base: https://github.com/ARM-software
    - name: ARMmbed
      url-base: https://github.com/ARMmbed

  #
  # Please add items below based on alphabetical order
  projects:
    - name: cmsis
      revision: bfa48a337e6fe08187d86f7ba7bbca0626475e17
      path: modules/hal/cmsis
    - name: hal_atmel
      revision: c6825eab4a3eabe901d25259080f1f3661c8a7b6
      path: modules/hal/atmel
    - name: hal_altera
      revision: 23c1c1dd7a0c1cc9a399509d1819375847c95b97
      path: modules/hal/altera
    - name: canopennode
      path: modules/lib/canopennode
      revision: 5c6b0566d56264efd4bf23ed58bc7cb8b32fe063
    - name: ci-tools
      revision: cf55a47d52d38af655f3efa6d38ff105b727358a
      path: tools/ci-tools
    - name: civetweb
      revision: 99129c5efc907ea613c4b73ccff07581feb58a7a
      path: modules/lib/civetweb
    - name: esp-idf
      revision: 6835bfc741bf15e98fb7971293913f770df6081f
      path: modules/hal/esp-idf
    - name: fatfs
      revision: 9ee6b9b9511151d0d64a74d532d39c6f2bbd4f16
      path: modules/fs/fatfs
    - name: hal_cypress
      revision: a12d92816a53a521d79cefcf5c38b9dc8a4fed6e
      path: modules/hal/cypress
    - name: hal_nordic
      revision: 1ebfdf148b2ca1d9ab9267ab2cd64cc00f32d505
      path: modules/hal/nordic
    - name: hal_openisa
      revision: 3b54187649cc9b37161d49918f1ad28ff7c7f830
      path: modules/hal/openisa
    - name: hal_microchip
      revision: 688cb7deebd5910357e35843595149b3feba2184
      path: modules/hal/microchip
    - name: hal_silabs
      revision: 78da967feeac0d51219ef733cc3ccf643336589f
      path: modules/hal/silabs
    - name: hal_st
      revision: fa481784b3c49780f18d50bafe00390ccb62b2ec
      path: modules/hal/st
    - name: hal_stm32
      revision: 37dcc0e120bb2bb99d3ee3b99dbbcf2bffe50258
      path: modules/hal/stm32
    - name: hal_ti
      revision: 7dcbff2d5994bc48dc3aa2a6af619dadf91d88db
      path: modules/hal/ti
    - name: libmetal
      revision: 60f40977eccb7e067a83933cec859e266bff4849
      path: modules/hal/libmetal
    - name: lvgl
      revision: 74fc2e753a997bd71cefa34dd9c56dcb954b42e2
      path: modules/lib/gui/lvgl
    - name: mbedtls
      revision: cf7020eb4c7ef93319f2d6d2403a21e12a879bf6
      path: modules/crypto/mbedtls
    - name: mcuboot
      revision: 80a76f4af4314635bef83272779ddbed6021fc32
      path: bootloader/mcuboot
    - name: mcumgr
      revision: 1843fdce2b008b45f9cc8b38dd9a57a575ab50f6
      path: modules/lib/mcumgr
    - name: net-tools
      revision: 1080094bc246357c6c35e80e8b2d5d0ce7e0d963
      path: tools/net-tools
    - name: hal_nxp
      revision: 60fe8c0ae6e24d165cf42770b95c7df22b778386
      path: modules/hal/nxp
    - name: open-amp
      revision: 5720c73ef3bd885824b2d2184f606443e03f73c4
      path: modules/lib/open-amp
    - name: loramac-node
      revision: 29e516ec585b1a909af2b5f1c60d83e7d4d563e3
      path: modules/lib/loramac-node
    - name: openthread
      revision: 2ac83762b87b9cbb7072e3bca663ac13708c17d9
      path: modules/lib/openthread
    - name: segger
      revision: 6fcf61606d6012d2c44129edc033f59331e268bc
      path: modules/debug/segger
    - name: tinycbor
      path: modules/lib/tinycbor
      revision: 40daca97b478989884bffb5226e9ab73ca54b8c4
    - name: tinycrypt
      path: modules/crypto/tinycrypt
      revision: 3e9a49d2672ec01435ffbf0d788db6d95ef28de0
    - name: littlefs
      path: modules/fs/littlefs
      revision: 0aefdda69d236cb01f932117c1f32e9da09c0ec3
    - name: mipi-sys-t
      path: modules/debug/mipi-sys-t
      revision: baf51863f19f009b92e762115ba5572a5b996b92
    - name: nrf_hw_models
      path: modules/bsim_hw_models/nrf_hw_models
      revision: fec69703cb1ca06fcdab6d5fde01274f0fc5c759
    - name: hal_xtensa
      revision: e7a57d0c252f9c5f3cab9d5ceadda8753cacee5b
      path: modules/hal/xtensa
    - name: edtt
      path: tools/edtt
      revision: c39888ff74acf421eeff9a7514fa9b172c3373f7
    - name: zephyr-tfm
      path: modules/tee/tfm
      revision: west
      url: https://github.com/oyvindronningstad/trusted-firmware-m-zephyr-module
    - name: trusted-firmware-m
      path: modules/tee/tfm/trusted-firmware-m
      remote: trustedfirmware-nordic
      revision: master
    - name: CMSIS_5
      path: modules/tee/tfm/CMSIS_5
      remote: ARM-software
      revision: 5.5.0
    - name: mbed-crypto
      path: modules/tee/tfm/mbed-crypto
      remote: ARMmbed
      revision: mbedcrypto-3.0.1
    - name: psa-arch-tests
      path: modules/tee/tfm/psa-arch-tests
      remote: ARM-software
      revision: v20.03_API1.0

  self:
    path: zephyr
    west-commands: scripts/west-commands.yml
