# The west manifest file for upstream Zephyr.
#
# The per-installation west configuration file, .west/config, sets the
# path to the project containing this file in the [manifest] section's
# "path" variable.
#
# You are free to create your own manifest files and put them in any
# repository you want, to create your own custom Zephyr installations.
# For example, you could create a manifest file in your own out of
# tree application directory, which would pull this zephyr repository
# in as an ordinary project.
#
# You can pass your manifest repositories to west init when creating a
# new Zephyr installation. See the west documentation for more
# information.

manifest:
  defaults:
    remote: upstream

  remotes:
    - name: upstream
      url-base: https://github.com/zephyrproject-rtos
    - name: babblesim
      url-base: https://github.com/BabbleSim

  group-filter: [-babblesim, -optional]

  #
  # Please add items below based on alphabetical order
  projects:
    - name: acpica
      revision: da5f2721e1c7f188fe04aa50af76f4b94f3c3ea3
      path: modules/lib/acpica
    - name: bsim
      repo-path: babblesim-manifest
      revision: 384a091445c57b44ac8cbd18ebd245b47c71db94
      path: tools/bsim
      groups:
        - babblesim
    - name: babblesim_base
      remote: babblesim
      repo-path: base.git
      path: tools/bsim/components
      revision: 19d62424c0802c6c9fc15528febe666e40f372a1
      groups:
        - babblesim
    - name: babblesim_ext_2G4_libPhyComv1
      remote: babblesim
      repo-path: ext_2G4_libPhyComv1.git
      path: tools/bsim/components/ext_2G4_libPhyComv1
      revision: 9018113a362fa6c9e8f4b9cab9e5a8f12cc46b94
      groups:
        - babblesim
    - name: babblesim_ext_2G4_phy_v1
      remote: babblesim
      repo-path: ext_2G4_phy_v1.git
      path: tools/bsim/components/ext_2G4_phy_v1
      revision: d47c6dd90035b41b14f6921785ccb7b8484868e2
      groups:
        - babblesim
    - name: babblesim_ext_2G4_channel_NtNcable
      remote: babblesim
      repo-path: ext_2G4_channel_NtNcable.git
      path: tools/bsim/components/ext_2G4_channel_NtNcable
      revision: 20a38c997f507b0aa53817aab3d73a462fff7af1
      groups:
        - babblesim
    - name: babblesim_ext_2G4_channel_multiatt
      remote: babblesim
      repo-path: ext_2G4_channel_multiatt.git
      path: tools/bsim/components/ext_2G4_channel_multiatt
      revision: bde72a57384dde7a4310bcf3843469401be93074
      groups:
        - babblesim
    - name: babblesim_ext_2G4_modem_magic
      remote: babblesim
      repo-path: ext_2G4_modem_magic.git
      path: tools/bsim/components/ext_2G4_modem_magic
      revision: cb70771794f0bf6f262aa474848611c68ae8f1ed
      groups:
        - babblesim
    - name: babblesim_ext_2G4_modem_BLE_simple
      remote: babblesim
      repo-path: ext_2G4_modem_BLE_simple.git
      path: tools/bsim/components/ext_2G4_modem_BLE_simple
      revision: 809ab073159c9ab6686c2fea5749b0702e0909f7
      groups:
        - babblesim
    - name: babblesim_ext_2G4_device_burst_interferer
      remote: babblesim
      repo-path: ext_2G4_device_burst_interferer.git
      path: tools/bsim/components/ext_2G4_device_burst_interferer
      revision: 5b5339351d6e6a2368c686c734dc8b2fc65698fc
      groups:
        - babblesim
    - name: babblesim_ext_2G4_device_WLAN_actmod
      remote: babblesim
      repo-path: ext_2G4_device_WLAN_actmod.git
      path: tools/bsim/components/ext_2G4_device_WLAN_actmod
      revision: 9cb6d8e72695f6b785e57443f0629a18069d6ce4
      groups:
        - babblesim
    - name: babblesim_ext_2G4_device_playback
      remote: babblesim
      repo-path: ext_2G4_device_playback.git
      path: tools/bsim/components/ext_2G4_device_playback
      revision: 85c645929cf1ce995d8537107d9dcbd12ed64036
      groups:
        - babblesim
    - name: babblesim_ext_libCryptov1
      remote: babblesim
      repo-path: ext_libCryptov1.git
      path: tools/bsim/components/ext_libCryptov1
      revision: eed6d7038e839153e340bd333bc43541cb90ba64
      groups:
        - babblesim
    - name: cmsis
      revision: 4b96cbb174678dcd3ca86e11e1f24bc5f8726da0
      path: modules/hal/cmsis
      groups:
        - hal
    - name: cmsis-dsp
      revision: ff7b5fd1ea5f094665c090c343ec44e74dc0b193
      path: modules/lib/cmsis-dsp
    - name: cmsis-nn
      revision: 0c8669d81381ccf3b1a01d699f3b68b50134a99f
      path: modules/lib/cmsis-nn
    - name: edtt
      revision: 64e5105ad82390164fb73fc654be3f73a608209a
      path: tools/edtt
      groups:
        - tools
    - name: fatfs
      revision: 427159bf95ea49b7680facffaa29ad506b42709b
      path: modules/fs/fatfs
      groups:
        - fs
    - name: hal_altera
      revision: 0d225ddd314379b32355a00fb669eacf911e750d
      path: modules/hal/altera
      groups:
        - hal
    - name: hal_ambiq
      revision: ff4ca358d730536addf336c40c3faa4ebf1df00a
      path: modules/hal/ambiq
      groups:
        - hal
    - name: hal_atmel
      revision: aad79bf530b69b72712d18873df4120ad052d921
      path: modules/hal/atmel
      groups:
        - hal
    - name: hal_espressif
      revision: 67fa60bdffca7ba8ed199aecfaa26f485f24878b
      path: modules/hal/espressif
      west-commands: west/west-commands.yml
      groups:
        - hal
    - name: hal_ethos_u
      revision: 90ada2ea5681b2a2722a10d2898eac34c2510791
      path: modules/hal/ethos_u
      groups:
        - hal
    - name: hal_gigadevice
      revision: 2994b7dde8b0b0fa9b9c0ccb13474b6a486cddc3
      path: modules/hal/gigadevice
      groups:
        - hal
    - name: hal_infineon
      revision: 69c883d3bd9fac8a18dd8384624b8c472a68d06f
      path: modules/hal/infineon
      groups:
        - hal
    - name: hal_intel
      revision: 7b4c25669f1513b0d6d6ee78ee42340d91958884
      path: modules/hal/intel
      groups:
        - hal
    - name: hal_microchip
      revision: 5d079f1683a00b801373bbbbf5d181d4e33b30d5
      path: modules/hal/microchip
      groups:
        - hal
    - name: hal_nordic
      revision: 4362d0fcdbac80942212bffc999654beac7ab30e
      path: modules/hal/nordic
      groups:
        - hal
    - name: hal_nuvoton
      revision: 68a91bb343ff47e40dbd9189a7d6e3ee801a7135
      path: modules/hal/nuvoton
      groups:
        - hal
    - name: hal_nxp
      revision: d45b14c198d778658b7853b48378d2e132a6c4be
      path: modules/hal/nxp
      groups:
        - hal
    - name: hal_openisa
      revision: eabd530a64d71de91d907bad257cd61aacf607bc
      path: modules/hal/openisa
      groups:
        - hal
    - name: hal_quicklogic
      revision: b3a66fe6d04d87fd1533a5c8de51d0599fcd08d0
      path: modules/hal/quicklogic
      repo-path: hal_quicklogic
      groups:
        - hal
    - name: hal_renesas
      path: modules/hal/renesas
      revision: 0b1f2fdb99d6386f125a8dba72083e3c56aecc2b
      groups:
        - hal
    - name: hal_rpi_pico
      path: modules/hal/rpi_pico
      revision: fba7162cc7bee06d0149622bbcaac4e41062d368
      groups:
        - hal
    - name: hal_silabs
      revision: b11b29167f3f9a0fd0c34a8eeeb36b0c1d218917
      path: modules/hal/silabs
      groups:
        - hal
    - name: hal_st
      revision: 0643d20ae85b32c658ad11036f7c964a860ddefe
      path: modules/hal/st
      groups:
        - hal
    - name: hal_stm32
      revision: 60c9634f61c697e1c310ec648d33529712806069
      path: modules/hal/stm32
      groups:
        - hal
    - name: hal_telink
      revision: 38573af589173259801ae6c2b34b7d4c9e626746
      path: modules/hal/telink
      groups:
        - hal
    - name: hal_ti
      revision: b85f86e51fc4d47c4c383d320d64d52d4d371ae4
      path: modules/hal/ti
      groups:
        - hal
    - name: hal_wurthelektronik
      revision: e5bcb2eac1bb9639ce13b4dafc78eb254e014342
      path: modules/hal/wurthelektronik
      groups:
        - hal
    - name: hal_xtensa
      revision: 08325d6fb7190a105f5382d35e64ed2812c57cf4
      path: modules/hal/xtensa
      groups:
        - hal
    - name: hostap
      repo-path: hostap
      path: modules/lib/hostap
      revision: dee924caf7218d0ee2c2698c217559b1292a46d0
    - name: libmetal
      revision: 243eed541b9c211a2ce8841c788e62ddce84425e
      path: modules/hal/libmetal
      groups:
        - hal
    - name: liblc3
      revision: 1a5938ebaca4f13fe79ce074f5dee079783aa29f
      path: modules/lib/liblc3
    - name: littlefs
      path: modules/fs/littlefs
      groups:
        - fs
      revision: 408c16a909dd6cf128874a76f21c793798c9e423
    - name: loramac-node
      revision: 842413c5fb98707eb5f26e619e8e792453877897
      path: modules/lib/loramac-node
    - name: lvgl
      revision: 2b76c641749725ac90c6ac7959ca7718804cf356
      path: modules/lib/gui/lvgl
    - name: mbedtls
      revision: 66ed2279d6222056af172c188eaf4dcfed481032
      path: modules/crypto/mbedtls
      groups:
        - crypto
    - name: mcuboot
      revision: a4eda30f5b0cfd0cf15512be9dcd559239dbfc91
      path: bootloader/mcuboot
    - name: mipi-sys-t
      path: modules/debug/mipi-sys-t
      groups:
        - debug
      revision: a819419603a2dfcb47f7f39092e1bc112e45d1ef
    - name: net-tools
      revision: 3a677d355cc7f73e444801a6280d0ccec80a1957
      path: tools/net-tools
      groups:
        - tools
    - name: nrf_hw_models
      revision: d17c9d749c817d2522468fa3c0eee3705feb8951
      path: modules/bsim_hw_models/nrf_hw_models
    - name: open-amp
      revision: da78aea63159771956fe0c9263f2e6985b66e9d5
      path: modules/lib/open-amp
    - name: openthread
      revision: 7761b81d23b10b3d5ee21b8504c67535cde10896
      path: modules/lib/openthread
    - name: percepio
      path: modules/debug/percepio
      revision: 0fbc5b72aeab8a6434523a3a7bc8111c17f0bc73
      groups:
        - debug
    - name: picolibc
      path: modules/lib/picolibc
      revision: 764ef4e401a8f4c6a86ab723533841f072885a5b
    - name: segger
      revision: 9d0191285956cef43daf411edc2f1a7788346def
      path: modules/debug/segger
      groups:
        - debug
    - name: tinycrypt
      revision: 3e9a49d2672ec01435ffbf0d788db6d95ef28de0
      path: modules/crypto/tinycrypt
      groups:
        - crypto
    - name: trusted-firmware-m
      revision: 58d0b5367f0fada9dbaddad1e08e302aeb044863
      path: modules/tee/tf-m/trusted-firmware-m
      groups:
        - tee
    - name: trusted-firmware-a
      revision: 421dc050278287839f5c70019bd6aec617f2bbdb
      path: modules/tee/tf-a/trusted-firmware-a
      groups:
        - tee
    - name: uoscore-uedhoc
      revision: 150f4eb2955eaf36ac0f9519d4f4f58d5ade5740
      path: modules/lib/uoscore-uedhoc
    - name: zcbor
      revision: d3093b5684f62268c7f27f8a5079f166772619de
      path: modules/lib/zcbor

  self:
    path: zephyr
    west-commands: scripts/west-commands.yml
    import: submanifests
