# The west manifest file for upstream Zephyr.
#
# The per-installation west configuration file, .west/config, sets the
# path to the project containing this file in the [manifest] section's
# "path" variable.
#
# You are free to create your own manifest files and put them in any
# repository you want, to create your own custom Zephyr installations.
# For example, you could create a manifest file in your own out of
# tree application directory, which would pull this zephyr repository
# in as an ordinary project.
#
# You can pass your manifest repositories to west init when creating a
# new Zephyr installation. See the west documentation for more
# information.

manifest:
  defaults:
    remote: upstream

  remotes:
    - name: upstream
      url-base: https://github.com/zephyrproject-rtos

  #
  # Please add items below based on alphabetical order
  projects:
    - name: cmsis
      revision: 542b2296e6d515b265e25c6b7208e8fea3014f90
      path: modules/hal/cmsis
    - name: hal_atmel
      revision: 1fe96f0a5e1a11d8101b258a3b84d35dc7178401
      path: modules/hal/atmel
    - name: hal_altera
      revision: 23c1c1dd7a0c1cc9a399509d1819375847c95b97
      path: modules/hal/altera
    - name: canopennode
      path: modules/lib/canopennode
      revision: 5c6b0566d56264efd4bf23ed58bc7cb8b32fe063
    - name: ci-tools
      revision: da9a2df574094f52d87a03f6393928bdc7dce17c
      path: tools/ci-tools
    - name: civetweb
      revision: 99129c5efc907ea613c4b73ccff07581feb58a7a
      path: modules/lib/civetweb
    - name: esp-idf
      revision: 6835bfc741bf15e98fb7971293913f770df6081f
      path: modules/hal/esp-idf
    - name: fatfs
      revision: 9ee6b9b9511151d0d64a74d532d39c6f2bbd4f16
      path: modules/fs/fatfs
    - name: hal_cypress
      revision: a12d92816a53a521d79cefcf5c38b9dc8a4fed6e
      path: modules/hal/cypress
    - name: hal_infineon
      revision: f1fa8241f8786198ba41155413243de36ed878a5
      path: modules/hal/infineon
    - name: hal_nordic
      revision: cb9e75ebfea8a8312678b2359c6b41b051a95177
      path: modules/hal/nordic
    - name: hal_openisa
      revision: 40d049f69c50b58ea20473bee14cf93f518bf262
      path: modules/hal/openisa
    - name: hal_nuvoton
      revision: b4d31f33238713a568e23618845702fadd67386f
      path: modules/hal/nuvoton
    - name: hal_microchip
      revision: aad89bf0531a30dcd6c87e4065f1b973fb31c11f
      path: modules/hal/microchip
    - name: hal_silabs
      revision: 78da967feeac0d51219ef733cc3ccf643336589f
      path: modules/hal/silabs
    - name: hal_st
      revision: 5b3ec3e182d4310e8943cc34c6c70ae57d9711da
      path: modules/hal/st
    - name: hal_stm32
      revision: 6b330f0af95c867bf27534b3b58be03c0fb9e7ad
      path: modules/hal/stm32
    - name: hal_ti
      revision: aabc6a04a8e871cbb01e02c22bb409f68001dc64
      path: modules/hal/ti
    - name: libmetal
      revision: 87e9e7f2c5b4e238236fe703db61ba23e48dc2ef
      path: modules/hal/libmetal
    - name: lvgl
      revision: 74fc2e753a997bd71cefa34dd9c56dcb954b42e2
      path: modules/lib/gui/lvgl
    - name: mbedtls
      path: modules/crypto/mbedtls
      revision: 4bf099f1254332d16dcd931ccea0a88d24a7d3c7
    - name: mcuboot
      revision: d52aff5065ab5995f785877a834112461ff93526
      path: bootloader/mcuboot
    - name: mcumgr
      revision: 898a5a7f5224be8345e58eca3b9a84389ed61d15
      path: modules/lib/mcumgr
    - name: net-tools
      revision: 1c4fdba512b268033a4cf926bddd323866c3261a
      path: tools/net-tools
    - name: hal_nxp
      revision: 478f03a71256aeb2890e685ebf5a1dc6832a6b5f
      path: modules/hal/nxp
    - name: open-amp
      revision: 724f7e2a4519d7e1d40ef330042682dea950c991
      path: modules/lib/open-amp
    - name: loramac-node
      revision: 170a2579dd890f78f5056f0959cdb9c9bea259a1
      path: modules/lib/loramac-node
    - name: openthread
      revision: d216ec32cdb78ec873689234f710b3c9bb096bcd
      path: modules/lib/openthread
    - name: segger
      revision: 6fcf61606d6012d2c44129edc033f59331e268bc
      path: modules/debug/segger
    - name: tinycbor
      path: modules/lib/tinycbor
      revision: 40daca97b478989884bffb5226e9ab73ca54b8c4
    - name: tinycrypt
      path: modules/crypto/tinycrypt
      revision: 3e9a49d2672ec01435ffbf0d788db6d95ef28de0
    - name: littlefs
      path: modules/fs/littlefs
      revision: 9e4498d1c73009acd84bb36036ee5e2869112a6c
    - name: mipi-sys-t
      path: modules/debug/mipi-sys-t
      revision: 957d46bc3ce0d5f628f0d525196bb4db207672ee
    - name: nrf_hw_models
      path: modules/bsim_hw_models/nrf_hw_models
      revision: fec69703cb1ca06fcdab6d5fde01274f0fc5c759
    - name: hal_xtensa
      revision: e7a57d0c252f9c5f3cab9d5ceadda8753cacee5b
      path: modules/hal/xtensa
    - name: edtt
      path: tools/edtt
      revision: c39888ff74acf421eeff9a7514fa9b172c3373f7
    - name: trusted-firmware-m
      path: modules/tee/tfm
      revision: 58c70aeb9937c3b6b97a07cc654e48b2c56c258a

  self:
    path: zephyr
    west-commands: scripts/west-commands.yml
