# The west manifest file for upstream Zephyr.
#
# The per-installation west configuration file, .west/config, sets the
# path to the project containing this file in the [manifest] section's
# "path" variable.
#
# You are free to create your own manifest files and put them in any
# repository you want, to create your own custom Zephyr installations.
# For example, you could create a manifest file in your own out of
# tree application directory, which would pull this zephyr repository
# in as an ordinary project.
#
# You can pass your manifest repositories to west init when creating a
# new Zephyr installation. See the west documentation for more
# information.

manifest:
  defaults:
    remote: upstream

  remotes:
    - name: upstream
      url-base: https://github.com/zephyrproject-rtos
    - name: babblesim
      url-base: https://github.com/BabbleSim

  group-filter: [-babblesim, -optional]

  #
  # Please add items below based on alphabetical order
  projects:
    - name: acpica
      revision: 10ae1038e51eb9306f73c3bbcfc4fde954bb9625
      path: modules/lib/acpica
    - name: bsim
      repo-path: babblesim-manifest
      revision: 384a091445c57b44ac8cbd18ebd245b47c71db94
      path: tools/bsim
      groups:
        - babblesim
    - name: babblesim_base
      remote: babblesim
      repo-path: base.git
      path: tools/bsim/components
      revision: 19d62424c0802c6c9fc15528febe666e40f372a1
      groups:
        - babblesim
    - name: babblesim_ext_2G4_libPhyComv1
      remote: babblesim
      repo-path: ext_2G4_libPhyComv1.git
      path: tools/bsim/components/ext_2G4_libPhyComv1
      revision: 9018113a362fa6c9e8f4b9cab9e5a8f12cc46b94
      groups:
        - babblesim
    - name: babblesim_ext_2G4_phy_v1
      remote: babblesim
      repo-path: ext_2G4_phy_v1.git
      path: tools/bsim/components/ext_2G4_phy_v1
      revision: d47c6dd90035b41b14f6921785ccb7b8484868e2
      groups:
        - babblesim
    - name: babblesim_ext_2G4_channel_NtNcable
      remote: babblesim
      repo-path: ext_2G4_channel_NtNcable.git
      path: tools/bsim/components/ext_2G4_channel_NtNcable
      revision: 20a38c997f507b0aa53817aab3d73a462fff7af1
      groups:
        - babblesim
    - name: babblesim_ext_2G4_channel_multiatt
      remote: babblesim
      repo-path: ext_2G4_channel_multiatt.git
      path: tools/bsim/components/ext_2G4_channel_multiatt
      revision: bde72a57384dde7a4310bcf3843469401be93074
      groups:
        - babblesim
    - name: babblesim_ext_2G4_modem_magic
      remote: babblesim
      repo-path: ext_2G4_modem_magic.git
      path: tools/bsim/components/ext_2G4_modem_magic
      revision: cb70771794f0bf6f262aa474848611c68ae8f1ed
      groups:
        - babblesim
    - name: babblesim_ext_2G4_modem_BLE_simple
      remote: babblesim
      repo-path: ext_2G4_modem_BLE_simple.git
      path: tools/bsim/components/ext_2G4_modem_BLE_simple
      revision: 809ab073159c9ab6686c2fea5749b0702e0909f7
      groups:
        - babblesim
    - name: babblesim_ext_2G4_device_burst_interferer
      remote: babblesim
      repo-path: ext_2G4_device_burst_interferer.git
      path: tools/bsim/components/ext_2G4_device_burst_interferer
      revision: 5b5339351d6e6a2368c686c734dc8b2fc65698fc
      groups:
        - babblesim
    - name: babblesim_ext_2G4_device_WLAN_actmod
      remote: babblesim
      repo-path: ext_2G4_device_WLAN_actmod.git
      path: tools/bsim/components/ext_2G4_device_WLAN_actmod
      revision: 9cb6d8e72695f6b785e57443f0629a18069d6ce4
      groups:
        - babblesim
    - name: babblesim_ext_2G4_device_playback
      remote: babblesim
      repo-path: ext_2G4_device_playback.git
      path: tools/bsim/components/ext_2G4_device_playback
      revision: 85c645929cf1ce995d8537107d9dcbd12ed64036
      groups:
        - babblesim
    - name: babblesim_ext_libCryptov1
      remote: babblesim
      repo-path: ext_libCryptov1.git
      path: tools/bsim/components/ext_libCryptov1
      revision: eed6d7038e839153e340bd333bc43541cb90ba64
      groups:
        - babblesim
    - name: cmsis
      revision: 4b96cbb174678dcd3ca86e11e1f24bc5f8726da0
      path: modules/hal/cmsis
      groups:
        - hal
    - name: cmsis-dsp
      revision: ff7b5fd1ea5f094665c090c343ec44e74dc0b193
      path: modules/lib/cmsis-dsp
    - name: cmsis-nn
      revision: 0c8669d81381ccf3b1a01d699f3b68b50134a99f
      path: modules/lib/cmsis-nn
    - name: edtt
      revision: 64e5105ad82390164fb73fc654be3f73a608209a
      path: tools/edtt
      groups:
        - tools
    - name: fatfs
      revision: 427159bf95ea49b7680facffaa29ad506b42709b
      path: modules/fs/fatfs
      groups:
        - fs
    - name: hal_altera
      revision: 0d225ddd314379b32355a00fb669eacf911e750d
      path: modules/hal/altera
      groups:
        - hal
    - name: hal_ambiq
      revision: 0c5ea5749245c8ff6ce7aefbf0aa9981943c2857
      path: modules/hal/ambiq
      groups:
        - hal
    - name: hal_atmel
      revision: 942d664e48f7a2725933a93facc112b87b1de32b
      path: modules/hal/atmel
      groups:
        - hal
    - name: hal_espressif
      revision: b3cb13f06586543ae1d156dc3e84b2fd3dc2f1fb
      path: modules/hal/espressif
      west-commands: west/west-commands.yml
      groups:
        - hal
    - name: hal_ethos_u
      revision: 90ada2ea5681b2a2722a10d2898eac34c2510791
      path: modules/hal/ethos_u
      groups:
        - hal
    - name: hal_gigadevice
      revision: 2994b7dde8b0b0fa9b9c0ccb13474b6a486cddc3
      path: modules/hal/gigadevice
      groups:
        - hal
    - name: hal_infineon
      revision: 69c883d3bd9fac8a18dd8384624b8c472a68d06f
      path: modules/hal/infineon
      groups:
        - hal
    - name: hal_intel
      revision: 7b4c25669f1513b0d6d6ee78ee42340d91958884
      path: modules/hal/intel
      groups:
        - hal
    - name: hal_microchip
      revision: 5d079f1683a00b801373bbbbf5d181d4e33b30d5
      path: modules/hal/microchip
      groups:
        - hal
    - name: hal_nordic
      revision: b9633ecea67bf52925d4c61455046223b46402b1
      path: modules/hal/nordic
      groups:
        - hal
    - name: hal_nuvoton
      revision: 584190e131655de1046088bd0d0735d83429ec7c
      path: modules/hal/nuvoton
      groups:
        - hal
    - name: hal_nxp
      revision: 69046233b7a7fac3138ae4dd5bcf6158e82529bb
      path: modules/hal/nxp
      groups:
        - hal
    - name: hal_openisa
      revision: d1e61c0c654d8ca9e73d27fca3a7eb3b7881cb6a
      path: modules/hal/openisa
      groups:
        - hal
    - name: hal_quicklogic
      revision: b3a66fe6d04d87fd1533a5c8de51d0599fcd08d0
      path: modules/hal/quicklogic
      repo-path: hal_quicklogic
      groups:
        - hal
    - name: hal_renesas
      path: modules/hal/renesas
      revision: 1471ed3cbf501434a5f3df2f9df520c3bd8e0258
      groups:
        - hal
    - name: hal_rpi_pico
      path: modules/hal/rpi_pico
      revision: fba7162cc7bee06d0149622bbcaac4e41062d368
      groups:
        - hal
    - name: hal_silabs
      revision: d191d981c4eb20c0c7445a4061fcdbcfa686113a
      path: modules/hal/silabs
      groups:
        - hal
    - name: hal_st
      revision: fb8e79d1a261fd02aadff7c142729f1954163cf3
      path: modules/hal/st
      groups:
        - hal
    - name: hal_stm32
      revision: 89ef0a3383edebf661073073bcdf6e2836fe90ee
      path: modules/hal/stm32
      groups:
        - hal
    - name: hal_telink
      revision: 38573af589173259801ae6c2b34b7d4c9e626746
      path: modules/hal/telink
      groups:
        - hal
    - name: hal_ti
      revision: b85f86e51fc4d47c4c383d320d64d52d4d371ae4
      path: modules/hal/ti
      groups:
        - hal
    - name: hal_wurthelektronik
      revision: 24ca9873c3d608fad1fea0431836bc8f144c132e
      path: modules/hal/wurthelektronik
      groups:
        - hal
    - name: hal_xtensa
      revision: 08325d6fb7190a105f5382d35e64ed2812c57cf4
      path: modules/hal/xtensa
      groups:
        - hal
    - name: hostap
      repo-path: hostap
      path: modules/lib/hostap
      revision: 7adaff26baa48e26a32c576125e0a749a5239b12
    - name: libmetal
      revision: 03140d7f4bd9ba474ebfbb6256e84a9089248e67
      path: modules/hal/libmetal
      groups:
        - hal
    - name: liblc3
      revision: 448f3de31f49a838988a162ef1e23a89ddf2d2ed
      path: modules/lib/liblc3
    - name: littlefs
      path: modules/fs/littlefs
      groups:
        - fs
      revision: ca583fd297ceb48bced3c2548600dc615d67af24
    - name: loramac-node
      revision: 842413c5fb98707eb5f26e619e8e792453877897
      path: modules/lib/loramac-node
    - name: lvgl
      revision: 7c61a4cec26402d20c845c95dcad0e39dcd319f8
      path: modules/lib/gui/lvgl
    - name: mbedtls
      revision: 7053083b0cff8462464e3cbb826e87852fc03da6
      path: modules/crypto/mbedtls
      groups:
        - crypto
    - name: mcuboot
      revision: 0c0470e294dcfb52aab92299356a5f3caa0aa52b
      path: bootloader/mcuboot
    - name: mipi-sys-t
      path: modules/debug/mipi-sys-t
      groups:
        - debug
      revision: a819419603a2dfcb47f7f39092e1bc112e45d1ef
    - name: net-tools
      revision: d68ee9d17648a1bb3729c2023abfcb735dfe92fa
      path: tools/net-tools
      groups:
        - tools
    - name: nrf_hw_models
      revision: a715dcc179f1a71f51c574165958b72fe932ae3f
      path: modules/bsim_hw_models/nrf_hw_models
    - name: open-amp
      revision: 214f9fc1539f8e5937c0474cb6ee29b6dcb2d4b8
      path: modules/lib/open-amp
    - name: openthread
      revision: 4ed44bc7d58d9a98c6cca13a50d38129045ab3df
      path: modules/lib/openthread
    - name: percepio
      path: modules/debug/percepio
      revision: 0fbc5b72aeab8a6434523a3a7bc8111c17f0bc73
      groups:
        - debug
    - name: picolibc
      path: modules/lib/picolibc
      revision: 1a5c603b9f8e228f9459bdafedad15ea28efc700
    - name: segger
      revision: 9d0191285956cef43daf411edc2f1a7788346def
      path: modules/debug/segger
      groups:
        - debug
    - name: tinycrypt
      revision: 3e9a49d2672ec01435ffbf0d788db6d95ef28de0
      path: modules/crypto/tinycrypt
      groups:
        - crypto
    - name: trusted-firmware-m
      revision: 33c0f47bcb19721a5c33e6fe1eee9225d00bb5bc
      path: modules/tee/tf-m/trusted-firmware-m
      groups:
        - tee
    - name: trusted-firmware-a
      revision: 421dc050278287839f5c70019bd6aec617f2bbdb
      path: modules/tee/tf-a/trusted-firmware-a
      groups:
        - tee
    - name: uoscore-uedhoc
      revision: 5fe2cb613bd7e4590bd1b00c2adf181ac0229379
      path: modules/lib/uoscore-uedhoc
    - name: zcbor
      revision: 67fd8bb88d3136738661fa8bb5f9989103f4599e
      path: modules/lib/zcbor

  self:
    path: zephyr
    west-commands: scripts/west-commands.yml
    import: submanifests
