sample:
  description: Prometheus Client Sample
  name: prometheus_client_sample
common:
  harness: net
  min_ram: 192
  tags:
    - http
    - net
    - server
    - socket
    - prometheus
  platform_exclude:
    - native_posix
    - native_posix/native/64
tests:
  sample.net.prometheus: {}
