/*
 * Copyright (c) 2025 Nordic Semiconductor ASA.
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef IRONSIDE_SE_MEMORY_MAP_H_
#define IRONSIDE_SE_MEMORY_MAP_H_

#include <nrfx.h>

#ifdef __cplusplus
extern "C" {
#endif

#define IRONSIDE_SE_RADIOCORE_IPC_BUFFER_ADDRESS (0x2f88f800UL)
#define IRONSIDE_SE_RADIOCORE_IPC_BUFFER_SIZE    (128)

#define IRONSIDE_SE_RADIOCORE_EVENT_REPORT_ADDRESS (0x2f88f880UL)
#define IRONSIDE_SE_RADIOCORE_EVENT_REPORT_SIZE    (256)

#define IRONSIDE_SE_RADIOCORE_BOOT_REPORT_ADDRESS (0x2f88f980UL)
#define IRONSIDE_SE_RADIOCORE_BOOT_REPORT_SIZE    (512)

#define IRONSIDE_SE_APPLICATION_IPC_BUFFER_START (0x2f88fb80UL)
#define IRONSIDE_SE_APPLICATION_IPC_BUFFER_SIZE  (128)

#define IRONSIDE_SE_APPLICATION_EVENT_REPORT_ADDRESS (0x2f88fc00UL)
#define IRONSIDE_SE_APPLICATION_EVENT_REPORT_SIZE    (256)

#define IRONSIDE_SE_APPLICATION_BOOT_REPORT_ADDRESS (0x2f88fd00UL)
#define IRONSIDE_SE_APPLICATION_BOOT_REPORT_SIZE    (512)

#if defined(NRF_APPLICATION)

#define IRONSIDE_SE_BOOT_REPORT_ADDRESS  IRONSIDE_SE_APPLICATION_BOOT_REPORT_ADDRESS
#define IRONSIDE_SE_BOOT_REPORT_SIZE     IRONSIDE_SE_APPLICATION_BOOT_REPORT_SIZE
#define IRONSIDE_SE_EVENT_REPORT_ADDRESS IRONSIDE_SE_APPLICATION_EVENT_REPORT_ADDRESS
#define IRONSIDE_SE_EVENT_REPORT_SIZE    IRONSIDE_SE_APPLICATION_EVENT_REPORT_SIZE
#define IRONSIDE_SE_BOOT_REPORT_ADDRESS  IRONSIDE_SE_APPLICATION_BOOT_REPORT_ADDRESS
#define IRONSIDE_SE_BOOT_REPORT_SIZE     IRONSIDE_SE_APPLICATION_BOOT_REPORT_SIZE

#elif defined(NRF_RADIOCORE)

#define IRONSIDE_SE_BOOT_REPORT_ADDRESS  IRONSIDE_SE_RADIOCORE_BOOT_REPORT_ADDRESS
#define IRONSIDE_SE_BOOT_REPORT_SIZE     IRONSIDE_SE_RADIOCORE_BOOT_REPORT_SIZE
#define IRONSIDE_SE_EVENT_REPORT_ADDRESS IRONSIDE_SE_RADIOCORE_EVENT_REPORT_ADDRESS
#define IRONSIDE_SE_EVENT_REPORT_SIZE    IRONSIDE_SE_RADIOCORE_EVENT_REPORT_SIZE
#define IRONSIDE_SE_BOOT_REPORT_ADDRESS  IRONSIDE_SE_RADIOCORE_BOOT_REPORT_ADDRESS
#define IRONSIDE_SE_BOOT_REPORT_SIZE     IRONSIDE_SE_RADIOCORE_BOOT_REPORT_SIZE

#endif

#define IRONSIDE_SE_UPDATE_BLOB_SIZE (160 * 1024)

#if defined(NRF54H20_XXAA)

#define IRONSIDE_SE_UPDATE_MIN_ADDRESS (0x0e100000)
#define IRONSIDE_SE_UPDATE_MAX_ADDRESS (0x0e200000 - IRONSIDE_SE_UPDATE_BLOB_SIZE)

#elif defined(NRF9230_ENGB_XXAA)

#define IRONSIDE_SE_UPDATE_MIN_ADDRESS (0x0e600000)
#define IRONSIDE_SE_UPDATE_MAX_ADDRESS (0x0e72f000 - IRONSIDE_SE_UPDATE_BLOB_SIZE)

#endif

#ifdef __cplusplus
}
#endif
#endif /* IRONSIDE_SE_MEMORY_MAP_H_ */
