/*
 * Copyright (c) 2026 Nordic Semiconductor ASA
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef IRONSIDE_SE_PERIPHERAL_INTERFACE_H_
#define IRONSIDE_SE_PERIPHERAL_INTERFACE_H_

#ifdef __cplusplus
extern "C" {
#endif

#define IRONSIDE_SE_APPLICATION_BELLBOARD_IPC_TX_BELL_IDX   12
#define IRONSIDE_SE_APPLICATION_BELLBOARD_IPC_RX_BELL_IDX   0
#define IRONSIDE_SE_APPLICATION_BELLBOARD_EVENT_RX_BELL_IDX 1

#define IRONSIDE_SE_RADIOCORE_BELLBOARD_IPC_TX_BELL_IDX   18
#define IRONSIDE_SE_RADIOCORE_BELLBOARD_IPC_RX_BELL_IDX   0
#define IRONSIDE_SE_RADIOCORE_BELLBOARD_EVENT_RX_BELL_IDX 1

#if defined(NRF_APPLICATION)

#define IRONSIDE_SE_BELLBOARD_IPC_TX_BELL_IDX   IRONSIDE_SE_APPLICATION_BELLBOARD_IPC_TX_BELL_IDX
#define IRONSIDE_SE_BELLBOARD_IPC_RX_BELL_IDX   IRONSIDE_SE_APPLICATION_BELLBOARD_IPC_RX_BELL_IDX
#define IRONSIDE_SE_BELLBOARD_EVENT_RX_BELL_IDX IRONSIDE_SE_APPLICATION_BELLBOARD_EVENT_RX_BELL_IDX

#elif defined(NRF_RADIOCORE)

#define IRONSIDE_SE_BELLBOARD_IPC_TX_BELL_IDX   IRONSIDE_SE_RADIOCORE_BELLBOARD_IPC_TX_BELL_IDX
#define IRONSIDE_SE_BELLBOARD_IPC_RX_BELL_IDX   IRONSIDE_SE_RADIOCORE_BELLBOARD_IPC_RX_BELL_IDX
#define IRONSIDE_SE_BELLBOARD_EVENT_RX_BELL_IDX IRONSIDE_SE_RADIOCORE_BELLBOARD_EVENT_RX_BELL_IDX

#endif

#ifdef __cplusplus
}
#endif
#endif /* IRONSIDE_SE_PERIPHERAL_INTERFACE_H_ */
