/*
 * Copyright (c) 2025 Nordic Semiconductor ASA.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
#include <uicr/uicr.h>

#define SPU121_ADDR  (0x5f8d0000UL)
#define SPU130_ADDR  (0x5f900000UL)
#define SPU131_ADDR  (0x5F920000UL)
#define SPU133_ADDR  (0x5F990000UL)
#define PPIB130_ADDR (0x5f925000UL)
#define PPIB133_ADDR (0x5f99d000UL)

/* FLPR ownership */
UICR_SPU_PERIPH_PERM_SET(SPU121_ADDR, 4, true, false, NRF_OWNER_APPLICATION);

/* PPR ownership */
UICR_SPU_PERIPH_PERM_SET(SPU130_ADDR, 8, true, false, NRF_OWNER_APPLICATION);

/* Non-secure GRTC channels */
UICR_SPU_FEATURE_GRTC_CC_SET(SPU133_ADDR, 8, false, NRF_OWNER_NONE);
UICR_SPU_FEATURE_GRTC_CC_SET(SPU133_ADDR, 9, false, NRF_OWNER_NONE);
UICR_SPU_FEATURE_GRTC_CC_SET(SPU133_ADDR, 10, false, NRF_OWNER_NONE);
UICR_SPU_FEATURE_GRTC_CC_SET(SPU133_ADDR, 11, false, NRF_OWNER_NONE);
UICR_SPU_FEATURE_GRTC_CC_SET(SPU133_ADDR, 12, false, NRF_OWNER_NONE);

/* Non-secure DPPIC130 channels */
UICR_SPU_FEATURE_DPPIC_CH_SET(SPU131_ADDR, 0, false, NRF_OWNER_NONE);
UICR_SPU_FEATURE_DPPIC_CH_SET(SPU131_ADDR, 2, false, NRF_OWNER_NONE);
UICR_SPU_FEATURE_DPPIC_CH_SET(SPU131_ADDR, 3, false, NRF_OWNER_NONE);

/* Non-secure DPPIC132 channels */
UICR_SPU_FEATURE_DPPIC_CH_SET(SPU133_ADDR, 0, false, NRF_OWNER_NONE);
UICR_SPU_FEATURE_DPPIC_CH_SET(SPU133_ADDR, 2, false, NRF_OWNER_NONE);
UICR_SPU_FEATURE_DPPIC_CH_SET(SPU133_ADDR, 3, false, NRF_OWNER_NONE);

UICR_IPCMAP_CHANNEL_CFG(0, NRF_DOMAIN_RADIOCORE, 2, NRF_DOMAIN_GLOBALSLOW, 2);
UICR_IPCMAP_CHANNEL_CFG(1, NRF_DOMAIN_GLOBALSLOW, 0, NRF_DOMAIN_RADIOCORE, 0);
UICR_IPCMAP_CHANNEL_CFG(2, NRF_DOMAIN_GLOBALSLOW, 2, NRF_DOMAIN_RADIOCORE, 2);

/* (DPPIC130 ch.0) <== (DPPIC132 ch.0) */
UICR_PPIB_PUBLISH_RECEIVE_ENABLE(PPIB130_ADDR, 8);
UICR_PPIB_SUBSCRIBE_SEND_ENABLE(PPIB133_ADDR, 0);

/* (DPPIC130 ch.2) <== (DPPIC132 ch.2) */
UICR_PPIB_PUBLISH_RECEIVE_ENABLE(PPIB130_ADDR, 10);
UICR_PPIB_SUBSCRIBE_SEND_ENABLE(PPIB133_ADDR, 2);

/* (DPPIC130 ch.3) ==> (DPPIC132 ch.3) */
UICR_PPIB_SUBSCRIBE_SEND_ENABLE(PPIB130_ADDR, 11);
UICR_PPIB_PUBLISH_RECEIVE_ENABLE(PPIB133_ADDR, 3);
