name: Publish BabbleSim Tests Results

on:
  workflow_run:
    workflows: ["BabbleSim Tests"]
    types:
      - completed
jobs:
  bsim-test-results:
    name: "Publish BabbleSim Test Results"
    runs-on: ubuntu-22.04
    if: github.event.workflow_run.conclusion != 'skipped'

    steps:
      - name: Download artifacts
        uses: dawidd6/action-download-artifact@bf251b5aa9c2f7eeb574a96ee720e24f801b7c11 # v6
        with:
          run_id: ${{ github.event.workflow_run.id }}

      - name: Publish BabbleSim Test Results
        uses: EnricoMi/publish-unit-test-result-action@78879197c58e9f9595bf33d2d9c446d344fcca57 # v2
        with:
          check_name: BabbleSim Test Results
          comment_mode: off
          commit: ${{ github.event.workflow_run.head_sha }}
          event_file: event/event.json
          event_name: ${{ github.event.workflow_run.event }}
          files: "bsim-test-results/**/bsim_results.xml"
