name: PR Metadata Check

on:
  pull_request:
    types:
      - synchronize
      - opened
      - reopened
      - labeled
      - unlabeled
      - edited

permissions:
  contents: read

jobs:
  do-not-merge:
    name: Prevent Merging
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Set up Python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
        with:
          python-version: 3.12
          cache: pip
          cache-dependency-path: scripts/requirements-actions.txt

      - name: Install Python dependencies
        run: |
          pip install -r scripts/requirements-actions.txt --require-hashes

      - name: Run the check script
        run: |
          ./scripts/ci/do_not_merge.py -p "${{ github.event.pull_request.number }}"

  empty_pr_description:
    if: ${{ github.event.pull_request.body == '' }}
    name: PR Description
    runs-on: ubuntu-24.04
    steps:
      - name: Check for PR description
        run: |
          echo "Pull request description cannot be empty."
          exit 1
